In [2]:
# All modules necessary to run this notebook

import pandas as pd
from itertools import combinations, chain

In [3]:
# Load dataframe into memory

path = "/Users/joshuaelms/Desktop/github_repos/CSCI-B365/Meteorology_Modeling_Project/data/pretty_data.csv"
df = pd.read_csv(path)

df

,ML CAPE,ML CIN,ML LCL,ML LFC,ML EL,ML LI,ML hght0c,ML cap,ML b3km,ML brn,...,lrat,tei,sb_tlcl,ml_tlcl,mu_tlcl,t500,sweat,kinx,crav,Hailstone Size
0,565.886137,-2.456216,591.712340,760.740300,10016.261419,-2.475117,3057.724668,NaN,164.527269,23.507197,...,6.069679,14.624760,16.369450,14.650496,16.369450,-15.9184,237.167161,27.148344,11784.929088,1.25
1,93.557330,-61.118000,818.659297,1485.730600,4147.988929,1.094013,2878.872717,NaN,43.581811,2.961764,...,5.573791,11.207180,14.814369,11.829009,14.814369,-15.5371,196.419861,27.202330,1995.924762,1.00
2,416.713894,-0.701233,682.113493,751.489413,7419.731564,-2.174859,3043.083673,14.93536,145.276881,15.405312,...,6.338184,24.258178,15.830423,13.206279,15.830423,-16.9460,195.164206,9.331257,8136.811509,1.00
3,1110.622796,-12.420499,536.926037,989.547800,11364.753475,-4.154931,3532.140768,NaN,172.484246,22.193236,...,6.614233,19.432405,18.284842,16.262729,17.999692,-15.3177,250.757864,21.326550,31959.336376,1.50
4,1107.162497,-12.514324,536.912773,1008.662600,11386.082876,-4.102513,3583.432806,NaN,181.416062,23.363115,...,6.578394,21.032620,18.199308,16.380479,18.092846,-15.2050,264.888229,20.604840,32653.287157,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29097,0.000000,0.000000,2343.569759,NaN,2343.569759,12.494209,3528.145294,NaN,0.000000,0.000000,...,7.248768,25.792261,1.717536,-5.193819,7.683926,-15.9886,296.701531,17.164210,0.000000,1.25
29098,0.000000,0.000000,2326.323051,NaN,2326.323051,14.986276,3497.386732,NaN,0.000000,0.000000,...,7.258029,27.763669,0.607784,-7.145827,7.955932,-16.1519,303.557106,19.452570,0.000000,1.00
29099,0.000000,0.000000,2690.384769,NaN,2690.384769,14.638317,3482.939445,NaN,0.000000,0.000000,...,7.280055,25.590055,-0.462974,-9.417577,4.940292,-16.2501,232.337003,11.883790,0.000000,1.00
29100,0.000000,0.000000,2807.261593,NaN,2807.261593,16.123160,3451.467575,NaN,0.000000,0.000000,...,7.248819,25.573522,-0.424774,-11.976938,1.702041,-16.5189,161.945441,6.005967,0.000000,0.88
29101,0.000000,0.000000,2902.643807,NaN,2902.643807,16.707049,3439.645042,NaN,0.000000,0.000000,...,7.299416,21.989349,-0.618173,-13.089147,-3.561992,-16.5451,157.894041,4.242470,0.000000,1.00

In [4]:
# Generate the correlation matrix for dataframe, show most strongly correlated variables to Hailstone Size

df_corr = df.corr()

df_corr["Hailstone Size"].abs().sort_values(ascending=False)

Hailstone Size    1.000000
ship              0.203719
crav              0.179000
lrat              0.161617
sweat             0.138882
MU LI             0.137036
SB LI             0.128339
ML LI             0.123399
SB CAPE           0.119698
MU CAPE           0.115961
DCAPE             0.113458
Shear 0-6 km      0.109000
ML CAPE           0.107440
ML EL             0.092197
SB EL             0.090327
stp_fixed         0.087747
MU EL             0.072912
tei               0.072430
SB LCL            0.071378
SB hght0c         0.070903
MU hght0c         0.070903
ML hght0c         0.070903
SB cap            0.068412
stp_mixed         0.068026
scp               0.063640
ebwd[0]           0.051901
pwat              0.049410
Eff SRH           0.047059
Eff Inflow        0.036898
mlmr              0.035647
ML LFC            0.033251
ML LCL            0.032367
ML b3km           0.029507
Shear 0-1 km      0.027687
mu_tlcl           0.027546
ML CIN            0.026495
MU cap            0.021769
MU brn            0.017402
ML brn            0.016907
SRH 0-1 km        0.016673
SB brn            0.016409
ml_tlcl           0.016282
SB CIN            0.015348
sb_tlcl           0.012252
MU b3km           0.008658
SRH 0-3 km        0.007508
kinx              0.007002
SB LFC            0.005912
SB b3km           0.005629
MU LFC            0.005061
t500              0.004464
MU LCL            0.003182
ML cap            0.003065
MU CIN            0.001754
Name: Hailstone Size, dtype: float64

In [10]:
# Generate the power set (without the empty set) for any given iterator
def power_set(iterable):
    pset = chain.from_iterable(combinations(iterable, r) for r in range(len(iterable)+1))
    return list(list(combo) for combo in pset if len(combo) > 0)


field_pset = power_set(df.columns)

field_pset